services:
  api:
    build:
      target: dev
    command: sh -c "while true; do sleep 3600; done"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - api-node-modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  api-node-modules:
